name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.102' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
      working-directory: Sentinel/Server
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Sentinel/Server
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: Sentinel.Tests
